2023-02-26 16:13:28.817 | ERROR    | service.autotest.service_runcase_manage:runCase:36 - module 'automaticTestingFramework.conf.env_conf' has no attribute 'CASE_DATA_PATH'
2023-02-26 16:16:46.059 | ERROR    | service.autotest.service_runcase_manage:runCase:36 - invalid character 'â€œ' (U+201C) (<string>, line 1)
2023-02-26 16:19:43.238 | ERROR    | service.autotest.service_runcase_manage:runCase:36 - invalid syntax (<string>, line 1)
